### PR TITLE
Fix 404 warnings for assets

### LINKED ISSUE #64: 404 Warning for assets
I've got 404 warnings for images, which could not load while testing. I don't want to test the images, just suppress the warnings. 

After some research something like this  
```
    files: [{
        pattern: './karma-test-shim.js',
        watched: true
      },
      {
        pattern: '../src/assets/img/*.png',
        watched: false, 
        included: false, 
        served: true
      }
    ],

    proxies: {
      '/assets/img/': '/base/src/assets/img/'
    },
```
in the karma.conf.js should help, but I've got still 

` WARN [web-server]: 404: /base/src/assets/img/ionic_logo.png `

I have fiddled around with the path expressions, but did't get it. 

If someone please could help, Here my example [https://github.com/11lein/ionic-unit-testing-example](https://github.com/11lein/ionic-unit-testing-example)

### PR DESCRIPTION
**Pull request by datencia**
Fix 404 warnings for images during karma unit testing.

image

Fix #64

### CODE REVIEW

**Comment by leifwells** [comment]
Questions: Am I to assume the new `karma.config.js` file on the project root is to facilitate the root of the project getting properly set? This is required so the images can be properly found? Or was there another reason?

**Comment by datencia** [comment]
you are right, it sets properly the root of the project so the images can be found.

Another way I've found to solve it is to set the `basePath` property from the `test-config/karma.conf.js` to `../` (and modifying the file paths):

```javascript
var webpackConfig = require('./webpack.test.js');
module.exports = function(config) {
  var _config = {
    basePath: '../',

    frameworks: ['jasmine'],

    files: [
      {
        pattern: './test-config/karma-test-shim.js',
        watched: true
      },
      {
        pattern: './src/assets/**/*',
        watched: false,
        included: false,
        served: true,
        nocache: false
      }
    ],

    proxies: {
        '/assets/': '/base/src/assets/'
    },

    preprocessors: {
      './test-config/karma-test-shim.js': ['webpack', 'sourcemap']
    },

    ...
};
```

With the last approach, we could omit the `karma.conf.js` file created in the root project folder.

**Comment by leifwells** [comment]
If we can keep all the configuration files inside the `test-config` folder, I think we should do that. If you have time to make this change to your PR, I'll be happy to review it over the weekend.

Also, I've had difficulty adding/locating/serving a `data.json` file with our current set up. Would this allow for files like this to also be located and used during testing?

Thanks for sorting this out!

**Comment by datencia** [comment]
Ok, I'll remove the `karma.conf.js` file from the project root folder. I created it to simplify the npm scripts commands (karma look at the project root folder for this file first) and to follow others project structures (as Angular CLI does).

Finally, this will allow you locate other files under the assets folder during testing as well. I've been able to load a JSON file using the real Angular's HTTP service inside a spec.

**Pull request merged**
